In [1]:
# 필요한 라이브러리
import requests
import json
import pandas as pd

In [3]:
df = pd.read_csv("seoul3_real_estate_1000.csv")
df.head()

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11530,구로구,10600,고척동,1.0,대지,0328,0000,양우,...,43500,59.94,0.00,6.0,NaN,20240316.0,2000.0,아파트,중개거래,서울 구로구
1,2024,11380,은평구,10500,구산동,1.0,대지,0211,0002,뉴아름빌(211-2),...,25000,42.40,25.00,5.0,NaN,20240315.0,2018.0,연립다세대,중개거래,서울 은평구
2,2024,11620,관악구,10100,봉천동,1.0,대지,1574,0001,생모리츠타운,...,11700,22.24,30.66,7.0,NaN,NaN,2007.0,오피스텔,중개거래,서울 관악구
3,2024,11530,구로구,10200,구로동,1.0,대지,0415,0044,미라벨,...,23000,29.39,18.00,2.0,NaN,NaN,2018.0,연립다세대,중개거래,서울 구로구
4,2024,11680,강남구,10300,개포동,1.0,대지,1224,0004,예가풍경채3차,...,61000,37.43,22.00,3.0,NaN,NaN,2019.0,연립다세대,중개거래,서울 용산구